const Tokens = {
    ASSIGN: "=",
    GOAL: "goal",
    GO: "go",
    COND: "case",
    REPEAT: "echo",
    ADDITION: "+",
    SUBTRACTION: "-",
    MULTIPLICATION: "*",
    DIVISION: "/",
    MOD: "%",
    FLRDIV: "$",
    IL: ">",
    IG: "<",
    ILE: ">=",
    IGE: "<=",
    EE: "==",
    NE: "!=",
    PARENTHESIS_OPEN: "(",
    PARENTHESIS_CLOSE: ")",
    BLOCKOPEN: "{",
    BLOCKCLOSE: "}",
};
export default Tokens;
